server:
  port: 9090
  servlet:
    context-path: /mall
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mall?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: sdytfsyzYP1314
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: localhost
    database: 0
    password:
    port: 6379
  data:
    elasticsearch:
      repositories:
        enabled: true
#      cluster-name: localhost:9300
    mongodb:
      host: localhost
      port: 27017
      database: mall-port
  elasticsearch:
    rest:
      uris: http://localhost:9200
  rabbitmq:
    virtual-host: /mall
    username: mall
    password: mall
    port: 5672
    host: localhost
druidDataSource:
  statViewServlet:
    loginUserName: papa
    loginUserPassword: 123456

jwt:
  tokenHead: Bearer
  tokenHeader: Authorization
  secret: papa
  expire: 604800
mybatis:
  mapper-locations:
    - classpath*:com/**/mapper/*.xml
    - classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
secure:
  ignored:
    urls:
      - /swagger-ui/
      - /swagger-resources/**
      - /**/v2/api-docs
      - /**/*.html
      - /**/*.js
      - /**/*.css
      - /**/*.png
      - /**/*.map
      - /favicon.ico
      - /actuator/**
      - /druid/**
      - /admin/login
      - /admin/register
      - /admin/info
      - /admin/logout
      - /minio/upload
redis:
  database: mall
  key:
    admin: "ums:admin"
    resourceList: "ums:resourceList"
  expire:
    common: 86400